USE [master]
GO
/****** Object:  Database [SMTP]    Script Date: 21-09-2024 20:43:55 ******/
CREATE DATABASE [SMTP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SMTP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\SMTP.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SMTP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\SMTP_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [SMTP] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SMTP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SMTP] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SMTP] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SMTP] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SMTP] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SMTP] SET ARITHABORT OFF 
GO
ALTER DATABASE [SMTP] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SMTP] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SMTP] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SMTP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SMTP] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SMTP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SMTP] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SMTP] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SMTP] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SMTP] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SMTP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SMTP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SMTP] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SMTP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SMTP] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SMTP] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SMTP] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SMTP] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SMTP] SET  MULTI_USER 
GO
ALTER DATABASE [SMTP] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SMTP] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SMTP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SMTP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SMTP] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SMTP] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [SMTP] SET QUERY_STORE = ON
GO
ALTER DATABASE [SMTP] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [SMTP]
GO
/****** Object:  StoredProcedure [dbo].[SP_MAIL_SAVE]    Script Date: 21-09-2024 20:43:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[SP_MAIL_SAVE]
	AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	SELECT GETDATE()
END
GO
USE [master]
GO
ALTER DATABASE [SMTP] SET  READ_WRITE 
GO
