USE [master]
GO
/****** Object:  Database [SSIS]    Script Date: 21-09-2024 20:45:41 ******/
CREATE DATABASE [SSIS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SSIS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\SSIS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SSIS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\SSIS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [SSIS] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SSIS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SSIS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SSIS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SSIS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SSIS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SSIS] SET ARITHABORT OFF 
GO
ALTER DATABASE [SSIS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SSIS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SSIS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SSIS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SSIS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SSIS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SSIS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SSIS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SSIS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SSIS] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SSIS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SSIS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SSIS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SSIS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SSIS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SSIS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SSIS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SSIS] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SSIS] SET  MULTI_USER 
GO
ALTER DATABASE [SSIS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SSIS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SSIS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SSIS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SSIS] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SSIS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [SSIS] SET QUERY_STORE = ON
GO
ALTER DATABASE [SSIS] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [SSIS]
GO
/****** Object:  Table [dbo].[Student]    Script Date: 21-09-2024 20:45:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Student](
	[StudentID] [nvarchar](50) NULL,
	[StudentName] [nvarchar](50) NULL,
	[Marks] [real] NULL,
	[Gender] [nvarchar](50) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[Student] ([StudentID], [StudentName], [Marks], [Gender]) VALUES (N'1001', N'Advait', 99, N'M')
GO
INSERT [dbo].[Student] ([StudentID], [StudentName], [Marks], [Gender]) VALUES (N'1002', N'Anaya', 100, N'F')
GO
INSERT [dbo].[Student] ([StudentID], [StudentName], [Marks], [Gender]) VALUES (N'1001', N'ADVAIT', 99, N'M')
GO
INSERT [dbo].[Student] ([StudentID], [StudentName], [Marks], [Gender]) VALUES (N'1002', N'ANAYA', 100, N'F')
GO
USE [master]
GO
ALTER DATABASE [SSIS] SET  READ_WRITE 
GO
