use hunt;
-- Generated by convert_sql_to_mysql.py
-- Source: Hunt.sql (SQL Server dump)
SET FOREIGN_KEY_CHECKS = 0;
SET SQL_MODE = 'NO_ENGINE_SUBSTITUTION';

CREATE TABLE IF NOT EXISTS TBL_OVI_RM_Hierarchy_Mapping (
    EmpCode VARCHAR(100) NOT NULL,
    EmpName VARCHAR(100) NOT NULL,
    EmpRole VARCHAR(50) NOT NULL,
    SupervisorCode VARCHAR(100) NOT NULL,
    SupervisorName VARCHAR(100) NOT NULL,
    SupervisorRole VARCHAR(100) NOT NULL,
    Business VARCHAR(100) NOT NULL,
    EmpEmail VARCHAR(100) NULL,
    CentralTeam VARCHAR(100) NULL,
    CreatedAt DATETIME NULL,
    CreatedBy VARCHAR(50) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS LoginAttempts (
  Id DECIMAL(18, 0) NOT NULL,
  Empcode varchar(50) NULL,
  Empname varchar(150) NULL,
  LoginTime datetime NULL,
  LogoutTime datetime NULL,
  Attempts int NULL,
  ProfileId int NULL,
  ProfileName varchar(150) NULL,
  Brcode int NULL,
  Brname varchar(150) NULL,
  IpAddress varchar(150) NULL,
  AssetCode varchar(50) NULL,
  Flag varchar(50) NULL,
  PRIMARY KEY (Id)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ProfileMaster (
  ProfileId DECIMAL(18, 0) NOT NULL,
  ProfileShortCode varchar(50) NULL,
  ProfileName varchar(150) NULL,
  ProfileDescription varchar(500) NULL,
  Maker varchar(50) NULL,
  MakerDate datetime NULL,
  Authorised TINYINT(1) NULL,
  Authoriser varchar(50) NULL,
  AuthoriseDate datetime NULL,
  Flag varchar(50) NULL,
  PRIMARY KEY (ProfileId)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tbl_API_hunt_Activity_Log_Tracker (
  Emp_Code varchar(50) NULL,
  Form_Name varchar(50) NULL,
  Module_Name varchar(50) NULL,
  Total_Count int NULL,
  Activity varchar(50) NULL,
  Activity_Details varchar(100) NULL,
  Activity_Date datetime NULL
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TBL_API_statusMaster (
  statusCode int NOT NULL,
  statusDescription varchar(150) NULL,
  PRIMARY KEY (statusCode)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tbl_API_MstApplications (
  Id int NOT NULL,
  APPShortName varchar(500) NULL,
  FullName varchar(500) NULL,
  Purpose varchar(1000) NULL,
  ITGRCName varchar(500) NULL,
  ITGRCCode varchar(500) NULL,
  HostingDC varchar(500) NULL,
  `status` int NULL,
  CreatedBy varchar(500) NULL,
  CreatedDate datetime NULL,
  UpdateBy varchar(25) NULL,
  UpdatedDate datetime NULL,
  HostingDC_DB varchar(500) NULL,
  PRIMARY KEY (Id)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TBL_API_HUNT_Integration (
  IntegrationId int NOT NULL,
  ProjectManagerBTG varchar(100) NULL,
  ProjectManagerIT varchar(100) NULL,
  ProjectName varchar(100) NULL,
  ProjectId varchar(100) NULL,
  PlannedGoLiveDate datetime NULL,
  BusinessJustification LONGTEXT NULL,
  BusinessSponsor varchar(100) NULL,
  ExecutiveSponsor varchar(100) NULL,
  CostCenterCode varchar(100) NULL,
  UserJourneyDocumentPath varchar(100) NULL,
  Feedback varchar(500) NULL,
  `Status` int NULL,
  CreatedBy varchar(100) NULL,
  CreatedAt datetime NULL,
  UpdatedBy varchar(100) NULL,
  UpdatedAt datetime NULL,
  Assign varchar(50) NULL,
  AssignFrom varchar(50) NULL,
  IntegrationDocumentPath varchar(100) NULL,
  ConsumerApplication varchar(100) NULL,
  BTG_USER varchar(50) NULL,
  IT_USER varchar(50) NULL,
  IT_ARCHITECTURE varchar(50) NULL,
  ChannelID varchar(50) NULL,
  ContainerName CHAR(10) NULL,
  RDConceptNote varchar(100) NULL,
  SequenceDiagram varchar(100) NULL,
  ExpectedServiceSpecificationDocument varchar(100) NULL,
  In_Platform varchar(50) NULL,
  Parent_IntegrationId int NULL,
  ConsumerApplicationId int NULL,
  PRIMARY KEY (IntegrationId),
  CONSTRAINT fk_Integration_Status FOREIGN KEY (`Status`) REFERENCES TBL_API_statusMaster (statusCode),
  CONSTRAINT fk_Integration_Parent FOREIGN KEY (Parent_IntegrationId) REFERENCES TBL_API_HUNT_Integration (IntegrationId),
  CONSTRAINT fk_Integration_ConsumerApp FOREIGN KEY (ConsumerApplicationId) REFERENCES tbl_API_MstApplications (Id)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tbl_API_hunt_Feedback (
  Feedback_Id int NOT NULL,
  Integration_Id int NULL,
  Feedback_Details LONGTEXT NULL,
  `Status` int NULL,
  Created_By varchar(30) NULL,
  Created_Date datetime NULL,
  IsActive TINYINT(1) NULL,
  Updated_By varchar(30) NULL,
  Updated_Date datetime NULL,
  AssignTo VARCHAR(20) NULL,
  AssignFrom VARCHAR(20) NULL,
  PRIMARY KEY (Feedback_Id),
  CONSTRAINT fk_Feedback_Integration FOREIGN KEY (Integration_Id) REFERENCES TBL_API_HUNT_Integration (IntegrationId)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tbl_API_hunt_Misccd (
  MisccdId int NULL,
  CDTP varchar(250) NULL,
  CDValDesc varchar(500) NULL,
  Seq int NULL,
  `Status` int NULL,
  LUSR varchar(20) NULL,
  LUDT varchar(20) NULL,
  LUTM varchar(20) NULL
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tbl_API_hunt_USER (
  Id int NOT NULL,
  EmpCode varchar(25) NULL,
  Role varchar(20) NULL,
  EmailId varchar(150) NULL,
  IsActive int NULL,
  LastSuccessLoginDate datetime NULL,
  CreatedBy varchar(25) NULL,
  CreatedDate datetime NULL,
  UpdateBy varchar(25) NULL,
  UpdatedDate datetime NULL,
  PRIMARY KEY (Id)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tbl_API_ApplicationsSPOC (
  Id int NOT NULL,
  APPID int NULL,
  APPShortName varchar(100) NULL,
  SPOCDepartment varchar(30) NULL,
  SpocEMPCode varchar(20) NULL,
  SPOCName varchar(150) NULL,
  EmailAddress varchar(250) NULL,
  SPOCLevel varchar(150) NULL,
  `status` int NULL,
  CreatedBy varchar(25) NULL,
  CreatedDate datetime NULL,
  UpdateBy varchar(25) NULL,
  UpdatedDate datetime NULL,
  PRIMARY KEY (Id),
  CONSTRAINT fk_SPOC_Application FOREIGN KEY (APPID) REFERENCES tbl_API_MstApplications (Id)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TBL_API_EXTERNALSERVICES (
  EXTERNALSERVICE_ID int NOT NULL,
  COD_SERVICE_ID LONGTEXT NULL,
  SERVICE_SIGNATURE LONGTEXT NULL,
  NAM_SERVICE_MIDDLEWARE varchar(50) NULL,
  SERVICE_DESC LONGTEXT NULL,
  SERVICE_PROVIDER LONGTEXT NULL,
  SERVICE_INTERFACE_TYPE varchar(50) NULL,
  SERVICE_CATEGORY LONGTEXT NULL,
  SERVICE_TYPE varchar(100) NULL,
  ORCHESTRATED_SERVICE_DTLS LONGTEXT NULL,
  OBP_SERVICE_URL_UAT LONGTEXT NULL,
  OBP_SERVICE_URL_PSUPP LONGTEXT NULL,
  OBP_SERVICE_URL_PROD LONGTEXT NULL,
  OBP_WSDL_URL LONGTEXT NULL,
  PRODUCT_PROCESSOR_WSDL LONGTEXT NULL,
  SERVICE_VERSION LONGTEXT NULL,
  NAM_CONTAINER LONGTEXT NULL,
  NAM_DOMAIN LONGTEXT NULL,
  OBP_REQUEST LONGTEXT NULL,
  OBP_RESPONSE LONGTEXT NULL,
  PRODUCT_PROCESSOR_URL_UAT LONGTEXT NULL,
  PRODUCT_PROCESSOR_URL_PSUPP LONGTEXT NULL,
  PRODUCT_PROCESSOR_URL_PROD LONGTEXT NULL,
  TXT_ERROR_DESC LONGTEXT NULL,
  CONNECT_TIMEOUT_VALUE LONGTEXT NULL,
  SOCKET_TIMEOUT_VALUE LONGTEXT NULL,
  NAM_WORKMANAGER LONGTEXT NULL,
  WORKMANAGER_MAX_THREADS LONGTEXT NULL,
  WORKMANAGER_CAPACITY LONGTEXT NULL,
  TXT_SECURITY_FEATURE_DESC LONGTEXT NULL,
  SERVICE_DOC_PATH LONGTEXT NULL,
  NAM_INITIATOR LONGTEXT NULL,
  DAT_GO_LIVE LONGTEXT NULL,
  JIRA_ID LONGTEXT NULL,
  TXT_REMARKS LONGTEXT NULL,
  FILLER_01 LONGTEXT NULL,
  FILLER_02 LONGTEXT NULL,
  FILLER_03 LONGTEXT NULL,
  FILLER_04 LONGTEXT NULL,
  FILLER_05 LONGTEXT NULL,
  FILLER_06 LONGTEXT NULL,
  FILLER_07 LONGTEXT NULL,
  FILLER_08 LONGTEXT NULL,
  FILLER_09 LONGTEXT NULL,
  FILLER_10 LONGTEXT NULL,
  FLG_MNT_STATUS LONGTEXT NULL,
  COD_MNT_ACTION LONGTEXT NULL,
  COD_LAST_MNT_MAKERID LONGTEXT NULL,
  COD_LAST_MNT_CHKRID LONGTEXT NULL,
  DAT_LAST_MNT LONGTEXT NULL,
  CTR_UPDAT_SRLNO LONGTEXT NULL,
  API_CAT varchar(50) NULL,
  VIRTUALIZED LONGTEXT NULL,
  AUTOMATED LONGTEXT NULL,
  DEPRICATED_API LONGTEXT NULL,
  REQUEST_SAMPLE LONGTEXT NULL,
  RESPONSE_SAMPLE LONGTEXT NULL,
  DOC_TYPE LONGTEXT NULL,
  DOMAIN_NAME varchar(50) NULL,
  API_TYPE_ varchar(100) NULL,
  PRIMARY KEY (EXTERNALSERVICE_ID)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TBL_API_Main (
  TBL_API_Main_ID int NOT NULL,
  COD_SERVICE_ID LONGTEXT NULL,
  SERVICE_SIGNATURE LONGTEXT NULL,
  NAM_SERVICE_MIDDLEWARE varchar(100) NULL,
  SERVICE_DESC LONGTEXT NULL,
  SERVICE_PROVIDER varchar(100) NULL,
  SERVICE_INTERFACE_TYPE varchar(100) NULL,
  SERVICE_CATEGORY varchar(100) NULL,
  SERVICE_TYPE varchar(100) NULL,
  ORCHESTRATED_SERVICE_DTLS LONGTEXT NULL,
  OBP_SERVICE_URL_UAT LONGTEXT NULL,
  OBP_SERVICE_URL_PSUPP LONGTEXT NULL,
  OBP_SERVICE_URL_PROD LONGTEXT NULL,
  OBP_WSDL_URL LONGTEXT NULL,
  PRODUCT_PROCESSOR_WSDL LONGTEXT NULL,
  SERVICE_VERSION int NULL,
  NAM_CONTAINER varchar(100) NULL,
  NAM_DOMAIN varchar(100) NULL,
  OBP_REQUEST LONGTEXT NULL,
  OBP_RESPONSE LONGTEXT NULL,
  PRODUCT_PROCESSOR_URL_UAT LONGTEXT NULL,
  PRODUCT_PROCESSOR_URL_PSUPP LONGTEXT NULL,
  PRODUCT_PROCESSOR_URL_PROD LONGTEXT NULL,
  TXT_ERROR_DESC LONGTEXT NULL,
  CONNECT_TIMEOUT_VALUE varchar(100) NULL,
  SOCKET_TIMEOUT_VALUE varchar(100) NULL,
  NAM_WORKMANAGER LONGTEXT NULL,
  WORKMANAGER_MAX_THREADS LONGTEXT NULL,
  WORKMANAGER_CAPACITY LONGTEXT NULL,
  TXT_SECURITY_FEATURE_DESC LONGTEXT NULL,
  SERVICE_DOC_PATH LONGTEXT NULL,
  NAM_INITIATOR LONGTEXT NULL,
  DAT_GO_LIVE datetime NULL,
  JIRA_ID LONGTEXT NULL,
  TXT_REMARKS LONGTEXT NULL,
  FILLER_01 LONGTEXT NULL,
  FILLER_02 LONGTEXT NULL,
  FILLER_03 LONGTEXT NULL,
  FILLER_04 LONGTEXT NULL,
  FILLER_05 LONGTEXT NULL,
  FILLER_06 LONGTEXT NULL,
  FILLER_07 LONGTEXT NULL,
  FILLER_08 LONGTEXT NULL,
  FILLER_09 LONGTEXT NULL,
  FILLER_10 LONGTEXT NULL,
  FLG_MNT_STATUS LONGTEXT NULL,
  COD_MNT_ACTION LONGTEXT NULL,
  COD_LAST_MNT_MAKERID LONGTEXT NULL,
  COD_LAST_MNT_CHKRID LONGTEXT NULL,
  DAT_LAST_MNT datetime NULL,
  CTR_UPDAT_SRLNO TINYINT(1) NULL,
  API_CAT LONGTEXT NULL,
  VIRTUALIZED LONGTEXT NULL,
  AUTOMATED LONGTEXT NULL,
  DEPRICATED_API LONGTEXT NULL,
  REQUEST_SAMPLE LONGTEXT NULL,
  RESPONSE_SAMPLE LONGTEXT NULL,
  DOC_TYPE LONGTEXT NULL,
  DOMAIN_NAME varchar(100) NULL,
  API_TYPE LONGTEXT NULL,
  FileName LONGTEXT NULL,
  PRIMARY KEY (TBL_API_Main_ID)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Tbl_API_FilePath (
  Tbl_API_FilePath_Id int NOT NULL,
  FileName LONGTEXT NULL,
  TBL_API_Main_ID int NULL,
  CreatedDate datetime NULL,
  UpdateDate datetime NULL,
  Active TINYINT(1) NULL,
  OBP_SERVICE_URL_UAT LONGTEXT NULL,
  APIAddFiles LONGTEXT NULL,
  PRIMARY KEY (Tbl_API_FilePath_Id),
  CONSTRAINT fk_FilePath_Main FOREIGN KEY (TBL_API_Main_ID) REFERENCES TBL_API_Main (TBL_API_Main_ID)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Tbl_API_Main_Schedule_ActivityLog (
  Id bigint NOT NULL,
  Errormsg LONGTEXT NULL,
  `Status` varchar(100) NULL,
  ModuleName varchar(50) NULL,
  InsertedOn datetime NULL,
  PRIMARY KEY (Id)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TBL_API_Main_Scheduler_Data (
  COD_SERVICE_ID LONGTEXT NULL,
  SERVICE_SIGNATURE LONGTEXT NULL,
  NAM_SERVICE_MIDDLEWARE varchar(100) NULL,
  SERVICE_DESC LONGTEXT NULL,
  SERVICE_PROVIDER varchar(100) NULL,
  SERVICE_INTERFACE_TYPE varchar(100) NULL,
  SERVICE_CATEGORY varchar(100) NULL,
  SERVICE_TYPE varchar(100) NULL,
  ORCHESTRATED_SERVICE_DTLS LONGTEXT NULL,
  OBP_SERVICE_URL_UAT LONGTEXT NULL,
  OBP_SERVICE_URL_PSUPP LONGTEXT NULL,
  OBP_SERVICE_URL_PROD LONGTEXT NULL,
  OBP_WSDL_URL LONGTEXT NULL,
  PRODUCT_PROCESSOR_WSDL LONGTEXT NULL,
  SERVICE_VERSION int NULL,
  NAM_CONTAINER varchar(100) NULL,
  NAM_DOMAIN varchar(100) NULL,
  OBP_REQUEST LONGTEXT NULL,
  OBP_RESPONSE LONGTEXT NULL,
  PRODUCT_PROCESSOR_URL_UAT LONGTEXT NULL,
  PRODUCT_PROCESSOR_URL_PSUPP LONGTEXT NULL,
  PRODUCT_PROCESSOR_URL_PROD LONGTEXT NULL,
  TXT_ERROR_DESC LONGTEXT NULL,
  CONNECT_TIMEOUT_VALUE varchar(100) NULL,
  SOCKET_TIMEOUT_VALUE varchar(100) NULL,
  NAM_WORKMANAGER LONGTEXT NULL,
  WORKMANAGER_MAX_THREADS LONGTEXT NULL,
  WORKMANAGER_CAPACITY LONGTEXT NULL,
  TXT_SECURITY_FEATURE_DESC LONGTEXT NULL,
  SERVICE_DOC_PATH LONGTEXT NULL,
  NAM_INITIATOR LONGTEXT NULL,
  DAT_GO_LIVE datetime NULL,
  JIRA_ID LONGTEXT NULL,
  TXT_REMARKS LONGTEXT NULL,
  FILLER_01 LONGTEXT NULL,
  FILLER_02 LONGTEXT NULL,
  FILLER_03 LONGTEXT NULL,
  FILLER_04 LONGTEXT NULL,
  FILLER_05 LONGTEXT NULL,
  FILLER_06 LONGTEXT NULL,
  FILLER_07 LONGTEXT NULL,
  FILLER_08 LONGTEXT NULL,
  FILLER_09 LONGTEXT NULL,
  FILLER_10 LONGTEXT NULL,
  FLG_MNT_STATUS LONGTEXT NULL,
  COD_MNT_ACTION LONGTEXT NULL,
  COD_LAST_MNT_MAKERID LONGTEXT NULL,
  COD_LAST_MNT_CHKRID LONGTEXT NULL,
  DAT_LAST_MNT datetime NULL,
  CTR_UPDAT_SRLNO TINYINT(1) NULL,
  API_CAT LONGTEXT NULL,
  VIRTUALIZED LONGTEXT NULL,
  AUTOMATED LONGTEXT NULL,
  DEPRICATED_API LONGTEXT NULL,
  REQUEST_SAMPLE LONGTEXT NULL,
  RESPONSE_SAMPLE LONGTEXT NULL,
  DOC_TYPE LONGTEXT NULL,
  DOMAIN_NAME varchar(100) NULL,
  API_TYPE LONGTEXT NULL
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TBL_API_Main_Temp (
  TBL_API_Main_ID int NOT NULL,
  COD_SERVICE_ID LONGTEXT NULL,
  SERVICE_SIGNATURE LONGTEXT NULL,
  NAM_SERVICE_MIDDLEWARE LONGTEXT NULL,
  SERVICE_DESC LONGTEXT NULL,
  SERVICE_PROVIDER LONGTEXT NULL,
  SERVICE_INTERFACE_TYPE LONGTEXT NULL,
  SERVICE_CATEGORY LONGTEXT NULL,
  SERVICE_TYPE LONGTEXT NULL,
  ORCHESTRATED_SERVICE_DTLS LONGTEXT NULL,
  OBP_SERVICE_URL_UAT LONGTEXT NULL,
  OBP_SERVICE_URL_PSUPP LONGTEXT NULL,
  OBP_SERVICE_URL_PROD LONGTEXT NULL,
  OBP_WSDL_URL LONGTEXT NULL,
  PRODUCT_PROCESSOR_WSDL LONGTEXT NULL,
  SERVICE_VERSION int NULL,
  NAM_CONTAINER LONGTEXT NULL,
  NAM_DOMAIN LONGTEXT NULL,
  OBP_REQUEST LONGTEXT NULL,
  OBP_RESPONSE LONGTEXT NULL,
  PRODUCT_PROCESSOR_URL_UAT LONGTEXT NULL,
  PRODUCT_PROCESSOR_URL_PSUPP LONGTEXT NULL,
  PRODUCT_PROCESSOR_URL_PROD LONGTEXT NULL,
  TXT_ERROR_DESC LONGTEXT NULL,
  CONNECT_TIMEOUT_VALUE int NULL,
  SOCKET_TIMEOUT_VALUE int NULL,
  NAM_WORKMANAGER LONGTEXT NULL,
  WORKMANAGER_MAX_THREADS LONGTEXT NULL,
  WORKMANAGER_CAPACITY LONGTEXT NULL,
  TXT_SECURITY_FEATURE_DESC LONGTEXT NULL,
  SERVICE_DOC_PATH LONGTEXT NULL,
  NAM_INITIATOR LONGTEXT NULL,
  DAT_GO_LIVE datetime NULL,
  JIRA_ID LONGTEXT NULL,
  TXT_REMARKS LONGTEXT NULL,
  FILLER_01 LONGTEXT NULL,
  FILLER_02 LONGTEXT NULL,
  FILLER_03 LONGTEXT NULL,
  FILLER_04 LONGTEXT NULL,
  FILLER_05 LONGTEXT NULL,
  FILLER_06 LONGTEXT NULL,
  FILLER_07 LONGTEXT NULL,
  FILLER_08 LONGTEXT NULL,
  FILLER_09 LONGTEXT NULL,
  FILLER_10 LONGTEXT NULL,
  FLG_MNT_STATUS LONGTEXT NULL,
  COD_MNT_ACTION LONGTEXT NULL,
  COD_LAST_MNT_MAKERID LONGTEXT NULL,
  COD_LAST_MNT_CHKRID LONGTEXT NULL,
  DAT_LAST_MNT datetime NULL,
  CTR_UPDAT_SRLNO TINYINT(1) NULL,
  API_CAT LONGTEXT NULL,
  VIRTUALIZED LONGTEXT NULL,
  AUTOMATED LONGTEXT NULL,
  DEPRICATED_API LONGTEXT NULL,
  REQUEST_SAMPLE LONGTEXT NULL,
  RESPONSE_SAMPLE LONGTEXT NULL,
  DOC_TYPE LONGTEXT NULL,
  DOMAIN_NAME LONGTEXT NULL,
  API_TYPE LONGTEXT NULL,
  PRIMARY KEY (TBL_API_Main_ID)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TBL_API_Master (
  API_Master_ID int NOT NULL,
  `Value` varchar(500) NULL,
  Description LONGTEXT NULL,
  PRIMARY KEY (API_Master_ID)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TBL_API_Master_Values (
  Id int NOT NULL,
  API_Master_ID int NULL,
  `Value` LONGTEXT NULL,
  Description LONGTEXT NULL,
  PRIMARY KEY (Id),
  CONSTRAINT fk_MasterValues_Master FOREIGN KEY (API_Master_ID) REFERENCES TBL_API_Master (API_Master_ID)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TBL_API_URLMaster (
  ID int NOT NULL,
  URLName varchar(100) NULL,
  URL varchar(500) NULL,
  `Status` int NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TBL_API_HUNT_APIDetails (
  API_ID int NOT NULL,
  ProjectManagerBTG varchar(100) NULL,
  ProjectManagerIT varchar(100) NULL,
  ProjectName varchar(100) NULL,
  ProjectId int NULL,
  GoLiveDate datetime NULL,
  BusinessJustification LONGTEXT NULL,
  BusinessSponsor varchar(100) NULL,
  ExecutiveSponsor varchar(100) NULL,
  CostCenterCode varchar(100) NULL,
  CollectionFileName varchar(100) NULL,
  APIName varchar(500) NULL,
  APIUrl varchar(200) NULL,
  Host varchar(200) NULL,
  Port int NULL,
  Endpoint varchar(100) NULL,
  MethodName varchar(100) NULL,
  APIHeader LONGTEXT NULL,
  RequestBody LONGTEXT NULL,
  ConsumerApplication varchar(100) NULL,
  ProducerApplication varchar(100) NULL,
  Middleware varchar(100) NULL,
  API_Type varchar(100) NULL,
  ServiceInterfaceType varchar(100) NULL,
  ServiceCategory varchar(100) NULL,
  ServiceDESC LONGTEXT NULL,
  ProductProcessor_WSDL varchar(100) NULL,
  ProductProcessor_URL_UAT varchar(100) NULL,
  ProductProcessor_URL_PSUPP varchar(100) NULL,
  ProductProcessor_URL_PROD varchar(100) NULL,
  IsDepricated TINYINT(1) NULL,
  IsOrchestrated TINYINT(1) NULL,
  IsStubAvailable TINYINT(1) NULL,
  IsHostedOnAPIGW TINYINT(1) NULL,
  CreatedBy varchar(100) NULL,
  CreatedAt datetime NULL,
  UpdatedBy varchar(100) NULL,
  UpdatedAt datetime NULL,
  PRIMARY KEY (API_ID)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tbl_API_HUNT_Partner_Onboarding (
  PartnetOnboading_ID int NOT NULL,
  Partner_Name varchar(50) NULL,
  Project_Description varchar(100) NULL,
  TentativeGoLive_Date date NULL,
  PartnerType varchar(100) NULL,
  PartnerEntityType varchar(100) NULL,
  PartnerTPRM_Application varchar(100) NULL,
  Partnerrisk_score varchar(100) NULL,
  Partnerrisk varchar(100) NULL,
  API_name varchar(100) NULL,
  API_risk varchar(100) NULL,
  APIrisk_score varchar(100) NULL,
  statusCode int NULL,
  created_By varchar(50) NULL,
  created_date datetime NULL,
  Updated_By varchar(20) NULL,
  Updated_date datetime NULL,
  AttachedJourneyDocuments varchar(150) NULL,
  APIRiskAssessment varchar(150) NULL,
  OtherDocument varchar(150) NULL,
  PRIMARY KEY (PartnetOnboading_ID),
  CONSTRAINT fk_PartnerOnboarding_Status FOREIGN KEY (statusCode) REFERENCES TBL_API_statusMaster (statusCode)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tbl_API_HUNT_Approval_trace_trial (
  Id int NOT NULL,
  caseID varchar(50) NULL,
  ApprovalTrialID varchar(50) NULL,
  Department varchar(100) NULL,
  ApprovalLevel varchar(20) NULL,
  ApprovalUserID varchar(50) NULL,
  Sequence int NULL,
  `Status` varchar(50) NULL,
  Feedback varchar(250) NULL,
  AssignTo varchar(50) NULL,
  AssignToLevel varchar(50) NULL,
  AssignToDept varchar(50) NULL,
  createdBy varchar(50) NULL,
  createdDate datetime NULL,
  UpdatedBy varchar(50) NULL,
  updatedDate datetime NULL,
  PRIMARY KEY (Id)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tbl_API_HUNT_PO_ApprovalTrailTable (
  Id int NOT NULL,
  CaseId varchar(50) NULL,
  Department varchar(100) NULL,
  ApproverLevel varchar(100) NULL,
  ApproverUserID varchar(100) NULL,
  Sequence varchar(10) NULL,
  `Status` varchar(50) NULL,
  PRIMARY KEY (Id)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tbl_API_HUNT_Audit_log (
  id int NOT NULL,
  CaseID int NULL,
  ApprovalID int NULL,
  `status` varchar(20) NULL,
  createdBy varchar(20) NULL,
  createdDate datetime NULL,
  Feedback varchar(250) NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_AuditLog_Case FOREIGN KEY (CaseID) REFERENCES tbl_API_HUNT_Partner_Onboarding (PartnetOnboading_ID),
  CONSTRAINT fk_AuditLog_Approval FOREIGN KEY (ApprovalID) REFERENCES tbl_API_HUNT_PO_ApprovalTrailTable (Id)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tbl_API_HUNT_ExceptionLevel (
  apiid int NOT NULL,
  ImpactOnbank varchar(50) NULL,
  Level varchar(20) NULL
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tbl_API_HUNT_ExceptionManagement (
  ID int NOT NULL,
  CaseId varchar(100) NULL,
  OriginalOnboardingGASID varchar(100) NULL,
  ExceptionRequestor varchar(100) NULL,
  APIProjectName varchar(100) NULL,
  APIProjectDescription varchar(100) NULL,
  PartnersToBeIntegrated varchar(100) NULL,
  ProductAPIToBeConsumed varchar(100) NULL,
  RequestedException varchar(100) NULL,
  ReasonForException varchar(100) NULL,
  StartDate date NULL,
  EndDate date NULL,
  HowExceptionToBeImplemented varchar(100) NULL,
  ImpactOnBank varchar(100) NULL,
  ExceptionLevel varchar(100) NULL,
  createdBy varchar(100) NULL,
  createdDate datetime NULL,
  updateBy varchar(100) NULL,
  updatedDate datetime NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tbl_API_HUNT_MstExceptionApprovalMetrix (
  ExceptionLevel varchar(100) NULL,
  ApproverType varchar(100) NULL,
  ApproverLevel varchar(100) NULL,
  ApproverUserID varchar(100) NULL,
  ApproverName varchar(100) NULL,
  ApproverEmail varchar(100) NULL
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tbl_API_HUNT_MstExepMetrix (
  ExceptionImpact varchar(50) NULL,
  ExceptionLevel varchar(50) NULL
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tbl_API_HUNT_MstPartnerCaseApprovalMetrix (
  PartnerRiskClassification varchar(100) NULL,
  APIRiskClassification varchar(100) NULL,
  ApproverType varchar(100) NULL,
  ApproverLevel varchar(100) NULL,
  ApproverUserID varchar(100) NULL,
  ApproverName varchar(100) NULL,
  ApproverEmail varchar(100) NULL,
  ApproverSequence varchar(100) NULL
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tbl_API_HUNT_MSTPartnerType (
  PartnerType varchar(100) NULL,
  PartnerEntityType varchar(100) NULL,
  TPRMAapplicable varchar(100) NULL
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TBL_API_HUNT_NewExceptionManagement (
  OriginalOnboardingGASID int NOT NULL,
  ExceptionRequestor varchar(100) NULL,
  APIProjectName varchar(100) NULL,
  APIProjectDescription varchar(100) NULL,
  PartenerstobeIntegrated varchar(100) NULL,
  ProductAPItobeConsumed varchar(100) NULL,
  RequestedException varchar(100) NULL,
  ReasonforException varchar(100) NULL,
  DurationofApproval varchar(100) NULL,
  HowExceptiontobeImplemented varchar(100) NULL,
  ToDate varchar(1) NULL,
  PRIMARY KEY (OriginalOnboardingGASID)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tbl_API_HUNT_PartnerCaseServiceList (
  CaseID int NOT NULL,
  APIName varchar(100) NULL,
  APIRiskClassification int NULL,
  APIRiskScore varchar(100) NULL,
  APIStatus varchar(100) NULL,
  CreatedBy varchar(100) NULL,
  DateCreated datetime NULL,
  DateUpdated date NULL
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tbl_API_HUNT_PartnerOffboardning_getdetails (
  Exit_Scenario varchar(100) NULL,
  Partner_Name varchar(100) NULL,
  API_Name varchar(100) NULL,
  Remark varchar(100) NULL,
  partner_checkilist varchar(100) NULL,
  fileUpload varchar(100) NULL,
  ID int NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tbl_API_HUNT_PartnerOnboarding (
  PartnetOnboadingID int NOT NULL,
  Partner_Name varchar(50) NULL,
  Project_Description varchar(100) NULL,
  `Tentative Go Live Date` datetime NULL,
  `Partner Type` varchar(50) NULL,
  `Partner Entity Type` varchar(50) NULL,
  `Partner TPRM Assessment Applicability` varchar(50) NULL,
  `Partner Risk Score` varchar(50) NULL,
  `Partner Risk` varchar(50) NULL,
  `API Name` varchar(50) NULL,
  `API Risk` varchar(50) NULL,
  `API Risk Score` varchar(50) NULL,
  PRIMARY KEY (PartnetOnboadingID)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tbl_API_HUNT_PO_ApiDeatil (
  Id int NOT NULL,
  CaseId varchar(50) NULL,
  APIName varchar(100) NULL,
  APIRisk varchar(100) NULL,
  APIRiskScore varchar(10) NULL,
  PRIMARY KEY (Id)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tbl_API_HUNT_PO_ApprovalTrailTable_New (
  Id int NOT NULL,
  CaseId varchar(50) NULL,
  Department varchar(100) NULL,
  ApproverLevel varchar(100) NULL,
  ApproverUserID varchar(100) NULL,
  Sequence varchar(10) NULL,
  `Status` varchar(50) NULL,
  PRIMARY KEY (Id)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tbl_API_HUNT_POCaseApproverMetrix (
  ID int NOT NULL,
  caseID int NULL,
  department varchar(50) NULL,
  Approver_level varchar(20) NULL,
  `status` varchar(20) NULL,
  emailid varchar(50) NULL,
  PRIMARY KEY (ID),
  CONSTRAINT fk_POCaseApprover_Case FOREIGN KEY (caseID) REFERENCES tbl_API_HUNT_Partner_Onboarding (PartnetOnboading_ID)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tbl_API_HUNT_POFeedbackReply_history (
  Id int NOT NULL,
  CaseID int NULL,
  ApprovalId int NULL,
  Department varchar(20) NULL,
  approvalLevel varchar(50) NULL,
  feedbackBy varchar(50) NULL,
  Role varchar(50) NULL,
  `Status` varchar(20) NULL,
  CreatedBy varchar(50) NULL,
  CreatedDate datetime NULL,
  Feedback_Reply varchar(100) NULL,
  feedbackReplyBy varchar(50) NULL,
  Feedback varchar(250) NULL,
  FeedbackID varchar(20) NULL,
  PRIMARY KEY (Id),
  CONSTRAINT fk_POFeedback_Case FOREIGN KEY (CaseID) REFERENCES tbl_API_HUNT_Partner_Onboarding (PartnetOnboading_ID),
  CONSTRAINT fk_POFeedback_Approval FOREIGN KEY (ApprovalId) REFERENCES tbl_API_HUNT_PO_ApprovalTrailTable (Id)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TBL_API_HUNT_Producer (
  ProducerId int NOT NULL,
  ApplicationName varchar(100) NULL,
  CreatedBy varchar(50) NULL,
  CreatedAt datetime NULL,
  UpdatedBy varchar(50) NULL,
  UpdatedAt datetime NULL,
  PRIMARY KEY (ProducerId)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TBL_API_HUNT_QuestionData (
  ID int NOT NULL,
  QID int NULL,
  Options varchar(1000) NULL,
  Weightage float NULL,
  `Status` int NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TBL_API_HUNT_ServiceQuestion (
  QID int NOT NULL,
  Question varchar(150) NULL,
  QuestionType varchar(20) NULL,
  APICategory varchar(20) NULL,
  `Status` int NULL,
  APICategoryId int NULL,
  PRIMARY KEY (QID)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TBL_API_HUNT_ServiceDetails (
  ServiceID int NOT NULL,
  IntegrationId int NULL,
  ServiceName LONGTEXT NULL,
  Purpose varchar(100) NULL,
  Existing_New varchar(100) NULL,
  ConsumerApplication varchar(100) NULL,
  ProducerApplication varchar(100) NULL,
  Is_APIGW_Request TINYINT(1) NULL,
  Rest_Soap varchar(100) NULL,
  Transformation varchar(100) NULL,
  Volume varchar(100) NULL,
  CreatedBy varchar(100) NULL,
  CreatedAt datetime NULL,
  UpdatedBy varchar(100) NULL,
  UpdatedAt datetime NULL,
  Existing_New_Id int NULL,
  Rest_SOAP_Id int NULL,
  ServiceType_Id int NULL,
  APIType_Id int NULL,
  APICategory_Id int NULL,
  APIRiskScore_Id int NULL,
  PartnerRiskScore_Id int NULL,
  DomainName_Id int NULL,
  ConsumerDC_Id int NULL,
  ProducerDC_Id int NULL,
  Platform varchar(50) NULL,
  QValue1 int NULL,
  QWeightage1 real NULL,
  QValue2 int NULL,
  QWeightage2 real NULL,
  QValue3 int NULL,
  QWeightage3 real NULL,
  QValue4 int NULL,
  QWeightage4 real NULL,
  QValue5 int NULL,
  QWeightage5 real NULL,
  RiskScore real NULL,
  Classification varchar(10) NULL,
  InternalServiceName LONGTEXT NULL,
  ExternalServiceName LONGTEXT NULL,
  ConsumerDC varchar(100) NULL,
  ProducerDC varchar(100) NULL,
  ExpectedServiceSpecificationDocument varchar(200) NULL,
  PRIMARY KEY (ServiceID),
  CONSTRAINT fk_ServiceDetails_Integration FOREIGN KEY (IntegrationId) REFERENCES TBL_API_HUNT_Integration (IntegrationId)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tbl_API_HUNT_QusServiceDetails (
  QusSerID int NOT NULL,
  ServiceID int NULL,
  QID int NULL,
  OptionsID int NULL,
  IsActive TINYINT(1) NULL,
  CreatedBy varchar(50) NULL,
  CreatedAt datetime NULL,
  UpdatedBy varchar(50) NULL,
  UpdatedAt datetime NULL,
  PRIMARY KEY (QusSerID),
  CONSTRAINT fk_QusService_Service FOREIGN KEY (ServiceID) REFERENCES TBL_API_HUNT_ServiceDetails (ServiceID),
  CONSTRAINT fk_QusService_Question FOREIGN KEY (QID) REFERENCES TBL_API_HUNT_ServiceQuestion (QID),
  CONSTRAINT fk_QusService_Options FOREIGN KEY (OptionsID) REFERENCES TBL_API_HUNT_QuestionData (ID)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS UserMaster (
  Id BIGINT AUTO_INCREMENT NOT NULL,
  EmpCode varchar(50) NULL,
  EmpName varchar(150) NULL,
  BranchCode DECIMAL(18, 0) NULL,
  BranchName varchar(150) NULL,
  ProfileDescription varchar(50) NULL,
  ProfileId DECIMAL(18, 0) NULL,
  Department varchar(150) NULL,
  SuperVisorCode varchar(50) NULL,
  LastLoginDate datetime NULL,
  LastLogoutDate datetime NULL,
  CreationDate datetime NULL,
  UnsuccessfulAttempts bigint NULL,
  Active TINYINT(1) NULL,
  LoggedIn TINYINT(1) NULL,
  Locked TINYINT(1) NULL,
  LockedDate datetime NULL,
  Dormant TINYINT(1) NULL,
  DormantDate datetime NULL,
  Enabled TINYINT(1) NULL,
  AssetCode varchar(50) NULL,
  IpAddress varchar(50) NULL,
  UserCategory varchar(50) NULL,
  ExpiryDate datetime NULL,
  Maker varchar(50) NULL,
  MakerDate datetime NULL,
  Checker varchar(50) NULL,
  CheckerDate datetime NULL,
  Reason LONGTEXT NULL,
  DeactivationDate datetime NULL,
  Flag varchar(50) NULL,
  Password varchar(50) NULL,
  PRIMARY KEY (Id),
  UNIQUE KEY uk_UserMaster_EmpCode (EmpCode),
  CONSTRAINT fk_UserMaster_Profile FOREIGN KEY (ProfileId) REFERENCES ProfileMaster (ProfileId)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;